exclude: ^(.*/data/.*)

repos:
  # Strip outputs from notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: "0.8.1"
    hooks:
      - id: nbstripout
        args:
          ["--extra-keys", "metadata.kernelspec metadata.language_info.version"]

  # The rest of the checks are from:
  # https://github.com/scientific-python/cookie/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.pre-commit-config.yaml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8"
  #   hooks:
  #     - id: prettier
  #       types_or: [yaml, markdown, html, css, scss, javascript, json]
  #       args: [--prose-wrap=always]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.1"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  # TODO: Enable type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.8.0"
  #   hooks:
  #     - id: mypy
  #       files: src|tests
  #       args: []
  #       additional_dependencies:
  #         - pytest

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.24.1"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.33.1"
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
