# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Include PDF and ePub
formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
    - dsecs_cp38_manylinux
