# Temporary environment configuration as a starting point
name: swarmx
channels:
  - conda-forge
dependencies:
  # IDE
  - python=3.10
  - pip
  - pipx
  - jupyterlab=3.2
  - code-server=3
  - jupyter-vscode-proxy=0.1
  # Dev tools (could be handled by nox)
  - pre-commit
  - pytest
  - sphinx
  - nox
  - flake8
  - black
  - flit
  - sphinx
  - myst-parser
  - sphinx-book-theme
  - sphinx-copybutton
  # Likely swarmx dependencies
  - dask=2022.1.1
  - xarray=0.21.1
  - pandas=1.4.0
  - numpy=1.22.2
  - scipy=1.8.0
  - cartopy=0.20.2
  - matplotlib=3.5.1
  - pip:
    - cdflib==0.3.20
    - viresclient==0.10.0
    - hapiclient==0.2.2
    # This package
    - -e .[dev]
