# Temporary environment configuration as a starting point
name: swarmpal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # Compiler required for apexpy
  - fortran-compiler
  # Dev tools (could be handled by nox)
  - pytest
  - sphinx
  - nox
  - flake8
  - black
  - flit
  - sphinx
  - myst-parser
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-autobuild
  # Necessary for tqdm progress bars to work in vscode
  - ipywidgets
  # Likely swarmpal minimum dependencies
  - cartopy
  - dask
  - matplotlib
  - numpy
  - pandas
  - scipy
  - viresclient
  - xarray
  - pip:
    - apexpy
    - hapiclient
    # This package
    - -e .[test,dev,docs,dsecs]
